### ISSUE TITLE
W0 - GitHub Pages Review

### ISSUE THREAD

**Issue by algolg** [algolg/akhil-t3#1]
Self Grade: 2/3 (4/5)
GitHub Page: [https://algolg.github.io/](https://algolg.github.io/)

- [ ]     (0/1) Navigates notes and plans for each Tech Talk
- I have notes on the Teach Talk from Week 0, but everything is on one page. In order to make my site more navigable, I should spread things across multiple pages
- [x]     (1/1) Contains Test Prep plans and participation for success on AP exam (required for test takers)
- I have a Test Prep plan. Like with the last requirement, I should probably move things over to their own pages.
- [x]     (1/1) Navigates to Data Structures work, contains code snippets on problems solutions, links to GitHub for Code, Replit for runtime, or alternatives
- I have a Replit deployment with an embed on my home page. My code is based off of Mr. M's solutions, but I added extra features, such as error handling for the menu for if users type an integer out of range or use the wrong data type, and an exit button.

**Comment by raad1masum** [comment]
# Raadwan's Review of Akhil - **2.75/3**
- **(1/1)** Navigates notes and plans for each Tech Talk
- **(1/1)** Contains Test Prep plans and participation for success on AP exam (required for test takers)
- **(0.75/1)** Navigates to Data Structures work, contains code snippets on problems solutions, links to GitHub for Code, Replit for runtime, or alternatives

Comments:
The GitHub pages site is made very well and I like the custom design. Almost all of the information is present. However, although there is a repl embed, there are no GitHub code snipets for the challenges (I took off 0.25 points for this). I would like to see code snippets using the three tilda notation in markdown. Overall, this site is looking very good.
