### ISSUE TITLE
[ W6 | AP-W1 ] 2015 MC and FRQ Ticket

### ISSUE THREAD

**Issue by algolg** [algolg/akhil-t3#12]
# Score: 4.75/5
## Reviewed By: Akshay
[Study Plan](https://github.com/algolg/akhil-t3/issues/13)
[MCQ Corrections](https://algolg.github.io/akhil-t3/mcq-corrections)
[Replit](https://replit.com/@algolg/akhil-t3)
[Study Guide](https://github.com/algolg/akhil-t3/issues/11)
[GitHub Pages](https://algolg.github.io/akhil-t3/index)

**Comment by Akshay-Rohatgi** [comment]
Robust and well-done FRQs and MCQ corrections, MCQ corrections show learning and improvement. FRQs are completed and running in REPL. Github Pages is well-made and easy to navigate. The study guide has room for improvement, more links to videos that you may plan to watch, or practice problems you might attempt. (-0.25)
