### ISSUE TITLE
W1 - Review Ticket

### ISSUE THREAD

**Issue by algolg** [algolg/akhil-t3#2]
Score: 4.75/5
Individual Reviewer: Raadwan

**Comment by raad1masum** [comment]
# Raadwan's Review of Akhil - **4.75/5**
- **(1/1)** Project Owner initial requirements and derivative tangibles
- **(1/1)** Requirements and Jobs assigned to each individuals listed on Scrum Board, including at least one in progress task
- **(1/1)** GitHub review page that documents key learnings using code snippets,
- **(1/1)** Replit for runtime to TT1 Challenges
- **(0.75/1)** Description of each element

Comments:
Once again, the GitHub pages site is made very well. The project owner is shown. The jobs for each individual are listed in the scrum board. The runtime works and includes all of the required features. One thing that was missing are the descriptions from the tech talks. I have taken off 0.25 points. If you want full points next time, you need to take notes during the tech talk.
