### ISSUE TITLE
W2 - Review Ticket

### ISSUE THREAD

**Issue by algolg** [algolg/akhil-t3#3]
Score: 6/5
Individual Reviewer: Raadwan

**Comment by raad1masum** [comment]
# Raadwan's Review of Akhil - **2.5/2**
- **(0.5/0.5)** GitHub review page that documents key learnings using code snippets
- **(2/1.5)** Calculator Code with optional extra credit functions, Replit Runtime, with runnable (no input) Test Data, and input option. 1.5

Comments:
All elements of the GitHub pages site are present. Notes on Week 2 are taken and put on the GitHub pages site. The calculator code runtime works and is deployed on the repl site. The extra credit elements are all present as well. This is great work and it deserves extra credit.
