### ISSUE TITLE
W3 - Review Ticket 2

### ISSUE THREAD

**Issue by algolg** [algolg/akhil-t3#5]
Score: 4.5/5
Grader: Prisha Maiti

https://algolg.github.io/akhil-t3/index.html

**Comment by PrishaMaiti** [comment]
Total Score: 4.5/5, Grader: Prisha Maiti
- Build custom Bubble Sort, Selection Sort, Insertion Sort and Merge Sort. 25%
He did Objective 2. All 3 sorts are there, but I don't see the 500 random pieces of data being sorted (he chose 500 over 5000). 1/1.25
- Build a GitHub page that describes Sort implementations and the Big O complexity of these Sorts. 25%
In the analysis, sort implementations are described and he says Merge Sort is the most efficient algorithm. The Big O complexity is also there. 1.25/1.25
- Analysis. 25%
Time analytic is there. Comparison analytic is there. I don't see a swap analytic. The rest of these requirements are explained above in the second requirement assessment. 1/1.25
- Individual GitHub pages, Replit, IntelliJ. 25%
GitHub Pages, both generic and for Sorts, are all there. Code runs on Replit and on IDE. Good amount of commits shown on repository. 1.25/1.25
